CREATE TABLE pacientes1-1 SELECT PAC_CODIGO, PAC_NOMEPESQ, PAC_PRONTUARIO,  PAC_CPF, PAC_SEXO, PAC_DTNASCIMENTO FROM paciente WHERE PAC_CODIGO BETWEEN 2001 AND 5000;

CREATE TABLE dipendereco2 SELECT PAC_CODIGO, PAC_LOGRADOURO, PAC_NUMERO, PAC_COMPLEMENTO, PAC_BAIRRO, PAC_CEP, UFE_SIGLA FROM paciente WHERE PAC_CODIGO BETWEEN 2000 AND 4000;